//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar a Familia.
        /// </summary>
        public static string AgregarAFamilia {
            get {
                return ResourceManager.GetString("AgregarAFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar a Perfil.
        /// </summary>
        public static string AgregarAPerfil {
            get {
                return ResourceManager.GetString("AgregarAPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes.
        /// </summary>
        public static string Ajustes {
            get {
                return ResourceManager.GetString("Ajustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir al Carrito.
        /// </summary>
        public static string AñadirCarrito {
            get {
                return ResourceManager.GetString("AñadirCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asociar Cliente.
        /// </summary>
        public static string AsociarCliente {
            get {
                return ResourceManager.GetString("AsociarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        public static string Ayuda {
            get {
                return ResourceManager.GetString("Ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido!.
        /// </summary>
        public static string Bienvenido {
            get {
                return ResourceManager.GetString("Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se bloqueo al usuario por demasiados intentos.
        /// </summary>
        public static string BlockingUser {
            get {
                return ResourceManager.GetString("BlockingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        public static string Cambiar {
            get {
                return ResourceManager.GetString("Cambiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        public static string CambiarContraseña {
            get {
                return ResourceManager.GetString("CambiarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Idioma.
        /// </summary>
        public static string CambiarIdioma {
            get {
                return ResourceManager.GetString("CambiarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga con exito.
        /// </summary>
        public static string CargaConExito {
            get {
                return ResourceManager.GetString("CargaConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar.
        /// </summary>
        public static string Cargar {
            get {
                return ResourceManager.GetString("Cargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrito creado con ID:.
        /// </summary>
        public static string CarritoCreado {
            get {
                return ResourceManager.GetString("CarritoCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear el carrito:.
        /// </summary>
        public static string CarritoError {
            get {
                return ResourceManager.GetString("CarritoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrito Id.
        /// </summary>
        public static string CarritoId {
            get {
                return ResourceManager.GetString("CarritoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrito no encontrado.
        /// </summary>
        public static string CarritoNotFound {
            get {
                return ResourceManager.GetString("CarritoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe cargar el carrito primero.
        /// </summary>
        public static string CarritoVacioException {
            get {
                return ResourceManager.GetString("CarritoVacioException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesion.
        /// </summary>
        public static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las claves son distintas.
        /// </summary>
        public static string ClavesDistintasException {
            get {
                return ResourceManager.GetString("ClavesDistintasException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente:.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe asociar un cliente al carrito.
        /// </summary>
        public static string ClienteAsociadoException {
            get {
                return ResourceManager.GetString("ClienteAsociadoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente asociado con exito.
        /// </summary>
        public static string ClienteAsociadoOK {
            get {
                return ResourceManager.GetString("ClienteAsociadoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobrar venta.
        /// </summary>
        public static string CobrarVenta {
            get {
                return ResourceManager.GetString("CobrarVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar.
        /// </summary>
        public static string Configurar {
            get {
                return ResourceManager.GetString("Configurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar Familias.
        /// </summary>
        public static string ConfigurarFamilias {
            get {
                return ResourceManager.GetString("ConfigurarFamilias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales invalidas.
        /// </summary>
        public static string CredencialesInvalidas {
            get {
                return ResourceManager.GetString("CredencialesInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CVV.
        /// </summary>
        public static string CVV {
            get {
                return ResourceManager.GetString("CVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Efectivo.
        /// </summary>
        public static string DatosEfectivo {
            get {
                return ResourceManager.GetString("DatosEfectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de Tarjeta.
        /// </summary>
        public static string DatosTarjeta {
            get {
                return ResourceManager.GetString("DatosTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Transferencia.
        /// </summary>
        public static string DatosTransferencia {
            get {
                return ResourceManager.GetString("DatosTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desbloqueado con exito.
        /// </summary>
        public static string DesbloqueadoConExito {
            get {
                return ResourceManager.GetString("DesbloqueadoConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desbloquear.
        /// </summary>
        public static string Desbloquear {
            get {
                return ResourceManager.GetString("Desbloquear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direccion.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dni.
        /// </summary>
        public static string Dni {
            get {
                return ResourceManager.GetString("Dni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efectivo.
        /// </summary>
        public static string Efectivo {
            get {
                return ResourceManager.GetString("Efectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elegir idioma: .
        /// </summary>
        public static string ElegirIdioma {
            get {
                return ResourceManager.GetString("ElegirIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminado con exito.
        /// </summary>
        public static string EliminadoConExito {
            get {
                return ResourceManager.GetString("EliminadoConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Producto.
        /// </summary>
        public static string EliminarProducto {
            get {
                return ResourceManager.GetString("EliminarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faltan completar campos.
        /// </summary>
        public static string FaltanCamposException {
            get {
                return ResourceManager.GetString("FaltanCamposException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una Familia con ese nombre.
        /// </summary>
        public static string FamiliaAlreadyExists {
            get {
                return ResourceManager.GetString("FamiliaAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias.
        /// </summary>
        public static string Familias {
            get {
                return ResourceManager.GetString("Familias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La familia ya existe en el arbol.
        /// </summary>
        public static string FamiliaYaExisteException {
            get {
                return ResourceManager.GetString("FamiliaYaExisteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Expiracion.
        /// </summary>
        public static string FechaExp {
            get {
                return ResourceManager.GetString("FechaExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de expiración no puede ser anterior al mes y año actuales..
        /// </summary>
        public static string FechaExpException {
            get {
                return ResourceManager.GetString("FechaExpException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de numero incorrecto.
        /// </summary>
        public static string FormatoIncorrecto {
            get {
                return ResourceManager.GetString("FormatoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FormCambiarIdioma.
        /// </summary>
        public static string FormCambiarIdioma {
            get {
                return ResourceManager.GetString("FormCambiarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FormCambiarPass.
        /// </summary>
        public static string FormCambiarPass {
            get {
                return ResourceManager.GetString("FormCambiarPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FormCobrarVenta.
        /// </summary>
        public static string FormCobrarVenta {
            get {
                return ResourceManager.GetString("FormCobrarVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FormGenerarCarrito.
        /// </summary>
        public static string FormGenerarCarrito {
            get {
                return ResourceManager.GetString("FormGenerarCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FormGenerarFactura.
        /// </summary>
        public static string FormGenerarFactura {
            get {
                return ResourceManager.GetString("FormGenerarFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FormGestionarFamilias.
        /// </summary>
        public static string FormGestionarFamilias {
            get {
                return ResourceManager.GetString("FormGestionarFamilias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FormGestionarPerfil.
        /// </summary>
        public static string FormGestionarPerfil {
            get {
                return ResourceManager.GetString("FormGestionarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FormGestionarProducto.
        /// </summary>
        public static string FormGestionarProducto {
            get {
                return ResourceManager.GetString("FormGestionarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FormGestionarUsuario.
        /// </summary>
        public static string FormGestionarUsuario {
            get {
                return ResourceManager.GetString("FormGestionarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede cerrar el formulario durante esta operacion.
        /// </summary>
        public static string FormNotClosable {
            get {
                return ResourceManager.GetString("FormNotClosable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FormRegistrarCliente.
        /// </summary>
        public static string FormRegistrarCliente {
            get {
                return ResourceManager.GetString("FormRegistrarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FormSeleccionarProducto.
        /// </summary>
        public static string FormSeleccionarProducto {
            get {
                return ResourceManager.GetString("FormSeleccionarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Carrito.
        /// </summary>
        public static string GenerarCarrito {
            get {
                return ResourceManager.GetString("GenerarCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Venta.
        /// </summary>
        public static string GenerarVenta {
            get {
                return ResourceManager.GetString("GenerarVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar Familias.
        /// </summary>
        public static string GestionarFamilias {
            get {
                return ResourceManager.GetString("GestionarFamilias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar Perfiles.
        /// </summary>
        public static string GestionarPerfiles {
            get {
                return ResourceManager.GetString("GestionarPerfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar Productos.
        /// </summary>
        public static string GestionarProductos {
            get {
                return ResourceManager.GetString("GestionarProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar Usuarios.
        /// </summary>
        public static string GestionarUsuarios {
            get {
                return ResourceManager.GetString("GestionarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        public static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay suficiente stock para el producto:.
        /// </summary>
        public static string InsuficienteStockException {
            get {
                return ResourceManager.GetString("InsuficienteStockException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir al carrito.
        /// </summary>
        public static string IrCarrito {
            get {
                return ResourceManager.GetString("IrCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comienza navegando por las opciones del menú para acceder a las funcionalidades que necesites, como registrar pedidos, gestionar inventario o generar informes. Si tienes alguna pregunta o necesitas ayuda, no dudes en contactar con el equipo de soporte..
        /// </summary>
        public static string MainMessage {
            get {
                return ResourceManager.GetString("MainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificado con exito..
        /// </summary>
        public static string ModificadoConExito {
            get {
                return ResourceManager.GetString("ModificadoConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        public static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto:.
        /// </summary>
        public static string Monto {
            get {
                return ResourceManager.GetString("Monto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto del cliente.
        /// </summary>
        public static string MontoCliente {
            get {
                return ResourceManager.GetString("MontoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, complete el monto del cliente..
        /// </summary>
        public static string MontoClienteMissing {
            get {
                return ResourceManager.GetString("MontoClienteMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El monto no es suficiente.
        /// </summary>
        public static string MontoInsuficiente {
            get {
                return ResourceManager.GetString("MontoInsuficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede agregar a un objeto patente.
        /// </summary>
        public static string NodoNoEsFamiliaException {
            get {
                return ResourceManager.GetString("NodoNoEsFamiliaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un nodo primero.
        /// </summary>
        public static string NodoNoSeleccionadoException {
            get {
                return ResourceManager.GetString("NodoNoSeleccionadoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha seleccionado un nodo raiz.
        /// </summary>
        public static string NoEsRootException {
            get {
                return ResourceManager.GetString("NoEsRootException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede agregar la misma familia al arbol.
        /// </summary>
        public static string NoSePuedeAgregarMismaFamiliaException {
            get {
                return ResourceManager.GetString("NoSePuedeAgregarMismaFamiliaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede quitar el perfil, use el boton eliminar.
        /// </summary>
        public static string NoSePuedeEliminarRootException {
            get {
                return ResourceManager.GetString("NoSePuedeEliminarRootException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe el cliente con el id:.
        /// </summary>
        public static string NotFoundClient {
            get {
                return ResourceManager.GetString("NotFoundClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de Tarjeta.
        /// </summary>
        public static string NumeroTarjeta {
            get {
                return ResourceManager.GetString("NumeroTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se admiten numeros.
        /// </summary>
        public static string OnlyNumbers {
            get {
                return ResourceManager.GetString("OnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una patente.
        /// </summary>
        public static string PatenteNoSeleccionadaException {
            get {
                return ResourceManager.GetString("PatenteNoSeleccionadaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes.
        /// </summary>
        public static string Patentes {
            get {
                return ResourceManager.GetString("Patentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La patente ya existe.
        /// </summary>
        public static string PatenteYaExisteException {
            get {
                return ResourceManager.GetString("PatenteYaExisteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfiles.
        /// </summary>
        public static string Perfiles {
            get {
                return ResourceManager.GetString("Perfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta seguro que desea cerrar la sesion?.
        /// </summary>
        public static string PreguntaCerrarSesion {
            get {
                return ResourceManager.GetString("PreguntaCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto eliminado del carrito correctamente..
        /// </summary>
        public static string ProductoEliminado {
            get {
                return ResourceManager.GetString("ProductoEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        public static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar.
        /// </summary>
        public static string Quitar {
            get {
                return ResourceManager.GetString("Quitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de expiración inválida. Use el formato MM/AA..
        /// </summary>
        public static string RegexFechaExpException {
            get {
                return ResourceManager.GetString("RegexFechaExpException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar Cliente.
        /// </summary>
        public static string RegistrarCliente {
            get {
                return ResourceManager.GetString("RegistrarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repita Contraseña.
        /// </summary>
        public static string RepitaContraseña {
            get {
                return ResourceManager.GetString("RepitaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen.
        /// </summary>
        public static string Resumen {
            get {
                return ResourceManager.GetString("Resumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un carrito.
        /// </summary>
        public static string SeleccionarCarritoException {
            get {
                return ResourceManager.GetString("SeleccionarCarritoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Producto.
        /// </summary>
        public static string SeleccionarProducto {
            get {
                return ResourceManager.GetString("SeleccionarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una familia primero.
        /// </summary>
        public static string SeleccioneFamiliaException {
            get {
                return ResourceManager.GetString("SeleccioneFamiliaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, seleccione una fila para eliminar..
        /// </summary>
        public static string SeleccionFilaEliminar {
            get {
                return ResourceManager.GetString("SeleccionFilaEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un producto primero.
        /// </summary>
        public static string SelectAProductException {
            get {
                return ResourceManager.GetString("SelectAProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al escribir en la base de datos:.
        /// </summary>
        public static string SqlException {
            get {
                return ResourceManager.GetString("SqlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay stock suficiente.
        /// </summary>
        public static string StockException {
            get {
                return ResourceManager.GetString("StockException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta.
        /// </summary>
        public static string Tarjeta {
            get {
                return ResourceManager.GetString("Tarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Pago.
        /// </summary>
        public static string TipoPago {
            get {
                return ResourceManager.GetString("TipoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titular.
        /// </summary>
        public static string Titular {
            get {
                return ResourceManager.GetString("Titular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas las Familias.
        /// </summary>
        public static string TodasFamilias {
            get {
                return ResourceManager.GetString("TodasFamilias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas las Patentes.
        /// </summary>
        public static string TodasPatentes {
            get {
                return ResourceManager.GetString("TodasPatentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los Perfiles.
        /// </summary>
        public static string TodosPerfiles {
            get {
                return ResourceManager.GetString("TodosPerfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total a Pagar:.
        /// </summary>
        public static string TotalPagar {
            get {
                return ResourceManager.GetString("TotalPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transferencia.
        /// </summary>
        public static string Transferencia {
            get {
                return ResourceManager.GetString("Transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario esta bloqueado.
        /// </summary>
        public static string UserIsBlocked {
            get {
                return ResourceManager.GetString("UserIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no esta activo.
        /// </summary>
        public static string UserIsNotActive {
            get {
                return ResourceManager.GetString("UserIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya se encuentra desbloqueado.
        /// </summary>
        public static string UsuarioAlreadyUnlocked {
            get {
                return ResourceManager.GetString("UsuarioAlreadyUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario ya existe.
        /// </summary>
        public static string UsuarioExisteException {
            get {
                return ResourceManager.GetString("UsuarioExisteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Venta Cerrada.
        /// </summary>
        public static string VentaCerrada {
            get {
                return ResourceManager.GetString("VentaCerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Venta cerrada, el vuelto es de:.
        /// </summary>
        public static string VentaCerradaPlusVuelto {
            get {
                return ResourceManager.GetString("VentaCerradaPlusVuelto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas.
        /// </summary>
        public static string Ventas {
            get {
                return ResourceManager.GetString("Ventas", resourceCulture);
            }
        }
    }
}
